language: cpp
compiler:
  - gcc

matrix:
  include:
    - os: linux
      services: docker
      sudo: required
      env: 
        - LEGACY=false
        - rootdir=/vw 
        - sh="docker exec -ti travis-ci bash -c"
    - os: linux
      sudo: required
      env:
        - LEGACY=true
        - rootdir=. 

before_install:
  - if [[ "$LEGACY" == "false" ]]; then docker pull ubuntu:16.04 ; fi
  - if [[ "$LEGACY" == "false" ]]; then docker run --name travis-ci -v $TRAVIS_BUILD_DIR:/vw -td ubuntu:16.04 /bin/bash ; fi

install:
  - $sh "cd $rootdir && ./travis-install.sh"

script:
  - $sh "cd $rootdir && ./travis-script.sh"
   
after_success:
  - $sh "coveralls --exclude lib --exclude tests --gcov-options '\-lp'"
