language: cpp
compiler:
  - gcc

matrix:
  include:
    - os: linux
      services: docker
      sudo: required
      env: 
        - LEGACY=false
        - DR="docker exec -ti travis-ci bash -c"
    - os: linux
      sudo: required
      env:
        - LEGACY=true

before_install:
  - if [[ "$LEGACY" == "false" ]]; then docker pull ubuntu:16.04 ; fi
  - if [[ "$LEGACY" == "false" ]]; then docker run --name travis-ci -v $TRAVIS_BUILD_DIR:/vw -td ubuntu:16.04 /bin/bash ; fi

install:
  - if [[ "$LEGACY" == "true" ]]; then ./travis-install.sh ; fi
  - if [[ "$LEGACY" == "false" ]]; then $DR "cd /vw && ./travis-install.sh"  ; fi

script:
  - if [[ "$LEGACY" == "true" ]]; then ./travis-script.sh ; fi
  - if [[ "$LEGACY" == "false" ]]; then $DR "cd /vw && ./travis-script.sh"  ; fi
   
after_success:
  - $sh "coveralls --exclude lib --exclude tests --gcov-options '\-lp'"
