matrix:
  include:
    - os: linux
      services: docker
      sudo: required
before_install:
  - docker pull eisber/vw
script:
  - docker run --name travis-ci -v $TRAVIS_BUILD_DIR:/vw -t eisber/vw /bin/bash -c "cd vw && ./build-linux.sh"
# after_success:
#  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
