language: cpp
compiler:
  - gcc

matrix:
  include:
    - os: linux
      services: docker
      sudo: required
      env: 
        - LEGACY=false
        - DR="docker exec -ti travis-ci bash -c"

before_install:
  - if [[ "$LEGACY" == "false" ]]; then docker pull eisber/vw ; fi
  - if [[ "$LEGACY" == "false" ]]; then docker run --name travis-ci -v $TRAVIS_BUILD_DIR:/vw -td eisber/vw /bin/bash ; fi


script:
  - if [[ "$LEGACY" == "false" ]]; then cmake . ; fi
  - if [[ "$LEGACY" == "false" ]]; then cmake --build . --target RunTests --target check -- -j 4 ; fi
