language: cpp
compiler:
  - gcc

matrix:
  include:
    - os: linux
      services: docker
      sudo: required
      env: LEGACY=false
      env: sh=docker exec -ti travis-ci bash -c
    - os: linux
      env: LEGACY=true
      env: sh=/bin/bash

before_install:
  - docker pull ubuntu:16.04
  - docker run --name travis-ci -v $TRAVIS_BUILD_DIR:/vw -td ubuntu:16.04 /bin/bash

install:
  - $sh /vw/travis-install.sh

script:
  - $sh /vw/travis-script.sh
   
after_success:
  - $sh "coveralls --exclude lib --exclude tests --gcov-options '\-lp'"
